import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNav from "@/components/nav";      // ✅ import your TopNav component
import Footer from "@/components/footer";  // ✅ import your Footer component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >

        <TopNav />         {/* ✅ Navbar always on top */}
        <main className="min-h-[60vh]">{children}</main>
        <Footer brandName="Your Brand" /> {/* ✅ Footer always at bottom */}
      </body>
    </html>
  );
}
